Crash report: 
Exception: 'float' object has no attribute 'to_value'
Traceback: 
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/./MaestroCore/database.py", line 60, in main
    module.update_database(dbPath)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/schedulerConfigs/Astrophotography/database_Astrophotography.py", line 52, in update_database
    candidates = Candidate.dfToCandidates(pd.read_csv("schedulerConfigs/Astrophotography/astroRes.csv"))
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 217, in dfToCandidates
    return [Candidate.fromDictionary(d) for d in df.to_dict(orient='records')]
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 200, in fromDictionary
    raise e
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 196, in fromDictionary
    return cls(CandidateName, CandidateType, **entry)  # splat
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 327, in __init__
    cand = associated_module.CandidateClass(CandidateName, **kwargs)
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/schedulerConfigs/Astrophotography/candidate_Astrophotography.py", line 46, in __init__
    super().__init__(self.CandidateName, self.CandidateType, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 114, in __init__
    self.__dict__[key] = self.config_serializers[schema["valtype"]](kwargs[key], **schema)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/candidateDatabase.py", line 70, in serialize_quantity
    print(quantity.to_value(unit))
          ^^^^^^^^^^^^^^^^^
